name: CI
on: { pull_request: {} }
jobs:
  test-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install pytest flake8
      - run: pytest -q lambdas/scanner && pytest -q lambdas/action && pytest -q lambdas/ai_insights
      - run: flake8 lambdas/scanner lambdas/action lambdas/ai_insights || true
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: aws-actions/amazon-ecr-login@v2
      - name: Build & push images (tag = PR SHA)
        run: |
          SHA="${{ github.sha }}"
          for svc in scanner action ai_insights; do
            REPO="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/levelup-costops-${svc%_*}"
            docker build -t "$REPO:$SHA" "lambdas/$svc"
            docker push "$REPO:$SHA"
          done
